version: 2.1
orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.20.0  # Updated to a compatible Node.js version
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  on_commit:
    jobs:
      - build_and_test
      # Uncomment the following when you have HEROKU_API_KEY & HEROKU_APP_NAME set up
      # - deploy:
      #     requires:
      #       - build_and_test
      #     filters:
      #       branches:
      #         only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_test
      # Uncomment the following when you have Heroku credentials set up
      # - deploy:
      #     requires:
      #       - build_and_test
      #     filters:
      #       branches:
      #         only: master