version: 2.1
orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          command: yarn test
          name: Run tests

  build:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --frozen-lockfile
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  version: 2
  
  # Workflow for pull requests and feature branches
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: 
                - main
                - master

  # Workflow for main branch
  main-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - main
                - master
      - build:
          requires:
            - test
          filters:
            branches:
              only: 
                - main
                - master
      # Uncomment when Heroku credentials are set up
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: 
      #           - main
      #           - master

  # Nightly build workflow
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - test
      - build:
          requires:
            - test
      # Uncomment when Heroku credentials are set up
      # - deploy:
      #     requires:
      #       - build